name = "imggul-background-worker"
main = "src/planner-background.js"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "imggul_db"
database_id = "cbc3c7dd-9028-4190-94a1-eee82216cd8b"

[[r2_buckets]]
binding = "imgBucket"
bucket_name = "imggul-storage"

[images]
binding = "IMAGES"

[[queues.consumers]]
queue = "imggul-queue"
max_batch_size = 1
max_batch_timeout = 30
max_retries = 2

[[queues.producers]]
binding = "GENERATION_QUEUE"
queue = "imggul-queue"
